<?xml version="1.0" encoding="utf-8"?><Database Name="DB_98559_comp" Class="sqlConClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=s13.winhost.com;Initial Catalog=DB_98559_comp;Persist Security Info=True;User ID=DB_98559_comp_user" SettingsObjectName="CompuTrack_Server.Properties.Settings" SettingsPropertyName="DB_98559_compConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tComputers" Member="tComputers">
    <Type Name="tComputer">
      <Column Name="compKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orgKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="make" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="model" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="osKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="compName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tComputer_tAlert" Member="tAlerts" ThisKey="compKey" OtherKey="alertAssetKey" Type="tAlert" />
      <Association Name="tComputer_tLiveDataHistory" Member="tLiveDataHistories" ThisKey="compKey" OtherKey="compKey" Type="tLiveDataHistory" />
      <Association Name="tComputer_tLiveData" Member="tLiveDatas" ThisKey="compKey" OtherKey="compKey" Type="tLiveData" />
      <Association Name="tOrg_tComputer" Member="tOrg" ThisKey="orgKey" OtherKey="orgKey" Type="tOrg" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tAlert" Member="tAlerts">
    <Type Name="tAlert">
      <Column Name="alertKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orgKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="alertName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="alertDesc" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="alertCreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="alertAssetKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="alertStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tComputer_tAlert" Member="tComputer" ThisKey="alertAssetKey" OtherKey="compKey" Type="tComputer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tUser" Member="tUsers">
    <Type Name="tUser">
      <Column Name="userKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orgKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="lname" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tOrg_tUser" Member="tOrg" ThisKey="orgKey" OtherKey="orgKey" Type="tOrg" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tOrg" Member="tOrgs">
    <Type Name="tOrg">
      <Column Name="orgKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orgName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="assetCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tOrg_tComputer" Member="tComputers" ThisKey="orgKey" OtherKey="orgKey" Type="tComputer" />
      <Association Name="tOrg_tUser" Member="tUsers" ThisKey="orgKey" OtherKey="orgKey" Type="tUser" />
    </Type>
  </Table>
  <Table Name="dbo.tLiveDataHistory" Member="tLiveDataHistories">
    <Type Name="tLiveDataHistory">
      <Column Name="liveDataHistoryKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="compKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cpuSpeed" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="cpuUsage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ramUsage" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="freeSpace" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="driveSize" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tComputer_tLiveDataHistory" Member="tComputer" ThisKey="compKey" OtherKey="compKey" Type="tComputer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tLiveData" Member="tLiveDatas">
    <Type Name="tLiveData">
      <Column Name="liveKey" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="compKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ram" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cpuSpeed" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="cpuUsage" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="freeSpace" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="activeApp" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ipAddr" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="lastSeen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tComputer_tLiveData" Member="tComputer" ThisKey="compKey" OtherKey="compKey" Type="tComputer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>